### ISSUE TITLE
팔로우 시 알림 기능 구현

### ISSUE THREAD

**Issue by haerimee** [f-lab-edu/ReadNShare#30]
## ToDo
- [X] Firebase SDK 설정 추가
- [X] 사용자 기기 식별 토큰 redis에 저장
- [X] 스프링 이벤트 발행 기능 이용(follow 이벤트)
- [X] 토큰을 통해 FCM 서버에 알림 요청
