### ISSUE TITLE
피드 조회 기능 구현

### ISSUE THREAD

**Issue by haerimee** [f-lab-edu/ReadNShare#34]
## ToDo

 - [x] Fan-out on read/write (Pull/Push Model) 정리 및 선택
 - [x] Redis 설정 추가
 - [x] 독서 기록 작성 시 피드 데이터 생성 구현
 - [x] 피드 조회 구현
 - [ ] 테스트 코드 작성
