### ISSUE TITLE
회원 가입 기능 구현

### ISSUE THREAD

**Issue by haerimee** [f-lab-edu/ReadNShare#4]
## ToDo
- [X] 유효성 검증
  - [X] 이메일 중복 체크
  - [X] 이메일 포맷
  - [X] 비밀번호 포맷

- [ ] 비밀번호 암호화 설정
- [X] 테스트 코드 작성
