### ISSUE TITLE
독서 기록 기능 구현

### ISSUE THREAD

**Issue by haerimee** [f-lab-edu/ReadNShare#9]
## ToDo

- 독서 기록 기능
    - [x] 독서 기록 저장 
    - [x] 독서 기록 수정
    - [x] 독서 기록 삭제
    
 - [x] 테스트 코드 작성
